### ISSUE TITLE
Bug: User has no permission executing commands

### ISSUE THREAD

**Issue by deltacomc** [bufanda/discord_bot#5]
User may not execute commands although he has the correct role

![grafik](https://github.com/user-attachments/assets/eb3286bf-d59b-4e3c-9589-e3436b00d56a)

**Comment by bufanda** [comment]
Check with `!member <username>` if bot_role in database is set to `user` and not `deny`. Bot-Role should be synced every 10 minutes.

**Comment by deltacomc** [comment]
!member scar user
!member
scar - Discord Role: @everyone,....- Bot Role: deny
